CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    password VARCHAR(255) NOT NULL,
    cpf CHAR(11) NOT NULL UNIQUE,
    imageProfile VARCHAR(255),
    isActive BOOLEAN NOT NULL DEFAULT TRUE,
    isStaff BOOLEAN NOT NULL DEFAULT FALSE, 
    isInstructor BOOLEAN NOT NULL DEFAULT FALSE,
    birthDate TIMESTAMP NOT NULL,
    lastLogin TIMESTAMP DEFAULT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);